source 'https://rubygems.org'

gem 'rails', '3.2.21'
gem 'rails-i18n'
gem 'devise'
gem 'devise-i18n'
gem 'devise-i18n-views'
gem 'state_machine'
gem 'yaml_db'
gem 'pg'
gem 'cancancan'
gem 'rabl'
gem 'jbuilder'
gem 'oj'
gem 'activeadmin', github: 'activeadmin'
gem 'jquery-rails'
gem 'thin'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end